# Generated by Django 4.2.20 on 2025-09-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_userprofile'),
    ]

    operations = [
    ]
