# Generated by Django 4.2.20 on 2025-09-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter phone number in format +1234567890', max_length=13, null=True, unique=True),
        ),
    ]
