# Generated by Django 4.2.20 on 2025-10-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_category_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-featured', '-created']},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_primary', 'display_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-featured', '-created']},
        ),
        migrations.AddField(
            model_name='category',
            name='color_class',
            field=models.CharField(default='primary', help_text="Bootstrap color class (e.g., 'primary', 'warning', 'info')", max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which categories are displayed (lower numbers first)'),
        ),
        migrations.AddField(
            model_name='category',
            name='featured',
            field=models.BooleanField(default=False, help_text='Display this category in featured sections'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_class',
            field=models.CharField(default='fas fa-box', help_text="Font Awesome icon class (e.g., 'fas fa-hammer')", max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='service_type',
            field=models.CharField(blank=True, choices=[('building-materials', 'Building Materials'), ('construction-tools', 'Construction Tools'), ('finishing-materials', 'Finishing Materials'), ('plumbing-supplies', 'Plumbing Supplies'), ('electrical-supplies', 'Electrical Supplies'), ('roofing-materials', 'Roofing Materials')], help_text='Select if this is one of the main service categories', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional order notes'),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, help_text='Feature this product on the homepage'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which images are displayed'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='featured',
            field=models.BooleanField(default=False, help_text='Feature this testimonial on product pages'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text="URL-friendly version of the name (e.g., 'building-materials')", unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('free', 'Free Delivery'), ('flat', 'Flat Rate Delivery'), ('express', 'Express Delivery')], default='free', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('material', 'Building Material'), ('tool', 'Construction Tool'), ('safety', 'Safety Equipment'), ('plumbing', 'Plumbing Item'), ('electrical', 'Electrical Item'), ('finishing', 'Finishing Material'), ('roofing', 'Roofing Material')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['paid', 'created'], name='store_order_paid_606019_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['featured', 'available'], name='store_produ_feature_091f94_idx'),
        ),
    ]
