# Generated by Django 4.2.20 on 2025-10-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='apply_price_increase',
            field=models.BooleanField(default=False, help_text='Apply 10% price increase when saving this product'),
        ),
    ]
