# Generated by Django 4.2.20 on 2025-11-17 18:58

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_apply_price_increase'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('icon_class', models.CharField(default='fas fa-cog', help_text='Font Awesome icon class for this group', max_length=50)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_name', models.CharField(help_text="Name of the specification (e.g., 'Power Consumption', 'Dimensions')", max_length=100)),
                ('spec_value', models.CharField(help_text="Value of the specification (e.g., '1500W', '120x80x150cm')", max_length=200)),
                ('spec_unit', models.CharField(blank=True, help_text="Unit of measurement (e.g., 'W', 'kg', 'mm')", max_length=50)),
                ('group', models.CharField(default='General', help_text="Group specifications (e.g., 'Electrical', 'Physical', 'Performance')", max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which specs are displayed within their group')),
                ('is_important', models.BooleanField(default=False, help_text='Mark as important to show in quick specs summary')),
            ],
            options={
                'verbose_name': 'Technical Specification',
                'verbose_name_plural': 'Technical Specifications',
                'ordering': ['group', 'display_order', 'spec_name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='has_technical_specs',
            field=models.BooleanField(default=False, help_text='Check if this product has technical specifications'),
        ),
        migrations.AddField(
            model_name='product',
            name='technical_data_sheet',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload PDF technical data sheet', max_length=255, null=True, verbose_name='technical_data_sheet'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['has_technical_specs'], name='store_produ_has_tec_4240bb_idx'),
        ),
        migrations.AddField(
            model_name='technicalspecification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_specs', to='store.product'),
        ),
    ]
